version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${{ secrets.MYSQL_HOST }}
      DB_PORT: 3306
      DB_NAME: recruit_board
      DB_USER: azureuser
      DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    ports:
      - "5000:5000"
    networks:
      - backend-network
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - backend-network
    depends_on:
      - backend

  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
